#!/bin/sh
# File generated by ocamlbuild

cd '/Users/jkim10/Documents/Spring 2020/PLT/microc (3)/_build'

rm -f ast.cmi
rm -f ast.cmo
rm -f ast.ml.depends
rm -f irgen.ml.depends
rm -f microc.ml.depends
rm -f microcparse.cmi
rm -f microcparse.ml
rm -f microcparse.mli
rm -f microcparse.mli.depends
rm -f sast.cmi
rm -f sast.cmo
rm -f sast.ml.depends
rm -f scanner.ml
rm -f scanner.ml.depends
rm -f semant.ml.depends
# Also clean the script itself
rm -f '/Users/jkim10/Documents/Spring 2020/PLT/microc (3)/_build/_build/sanitize.sh'
